/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as CarritoRouteImport } from './routes/carrito'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductoSlugRouteImport } from './routes/producto.$slug'
import { Route as CheckoutResultadoRouteImport } from './routes/checkout_.resultado'
import { Route as AuthenticatedCuentaRouteImport } from './routes/_authenticated/cuenta'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminNewRouteImport } from './routes/_authenticated/admin.new'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as AuthenticatedAdminEditIdRouteImport } from './routes/_authenticated/admin.edit.$id'

const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const CarritoRoute = CarritoRouteImport.update({
  id: '/carrito',
  path: '/carrito',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductoSlugRoute = ProductoSlugRouteImport.update({
  id: '/producto/$slug',
  path: '/producto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutResultadoRoute = CheckoutResultadoRouteImport.update({
  id: '/checkout_/resultado',
  path: '/checkout/resultado',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCuentaRoute = AuthenticatedCuentaRouteImport.update({
  id: '/cuenta',
  path: '/cuenta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminNewRoute = AuthenticatedAdminNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEditIdRoute =
  AuthenticatedAdminEditIdRouteImport.update({
    id: '/edit/$id',
    path: '/edit/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/carrito': typeof CarritoRoute
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/cuenta': typeof AuthenticatedCuentaRoute
  '/checkout/resultado': typeof CheckoutResultadoRoute
  '/producto/$slug': typeof ProductoSlugRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/new': typeof AuthenticatedAdminNewRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/edit/$id': typeof AuthenticatedAdminEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/carrito': typeof CarritoRoute
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRoute
  '/cuenta': typeof AuthenticatedCuentaRoute
  '/checkout/resultado': typeof CheckoutResultadoRoute
  '/producto/$slug': typeof ProductoSlugRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/new': typeof AuthenticatedAdminNewRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/edit/$id': typeof AuthenticatedAdminEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/carrito': typeof CarritoRoute
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/cuenta': typeof AuthenticatedCuentaRoute
  '/checkout_/resultado': typeof CheckoutResultadoRoute
  '/producto/$slug': typeof ProductoSlugRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/new': typeof AuthenticatedAdminNewRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/edit/$id': typeof AuthenticatedAdminEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/carrito'
    | '/catalogo'
    | '/checkout'
    | '/admin'
    | '/cuenta'
    | '/checkout/resultado'
    | '/producto/$slug'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/new'
    | '/admin/'
    | '/admin/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/carrito'
    | '/catalogo'
    | '/checkout'
    | '/cuenta'
    | '/checkout/resultado'
    | '/producto/$slug'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/new'
    | '/admin'
    | '/admin/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/carrito'
    | '/catalogo'
    | '/checkout'
    | '/_authenticated/admin'
    | '/_authenticated/cuenta'
    | '/checkout_/resultado'
    | '/producto/$slug'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/new'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CarritoRoute: typeof CarritoRoute
  CatalogoRoute: typeof CatalogoRoute
  CheckoutRoute: typeof CheckoutRoute
  CheckoutResultadoRoute: typeof CheckoutResultadoRoute
  ProductoSlugRoute: typeof ProductoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrito': {
      id: '/carrito'
      path: '/carrito'
      fullPath: '/carrito'
      preLoaderRoute: typeof CarritoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producto/$slug': {
      id: '/producto/$slug'
      path: '/producto/$slug'
      fullPath: '/producto/$slug'
      preLoaderRoute: typeof ProductoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout_/resultado': {
      id: '/checkout_/resultado'
      path: '/checkout/resultado'
      fullPath: '/checkout/resultado'
      preLoaderRoute: typeof CheckoutResultadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/cuenta': {
      id: '/_authenticated/cuenta'
      path: '/cuenta'
      fullPath: '/cuenta'
      preLoaderRoute: typeof AuthenticatedCuentaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/new': {
      id: '/_authenticated/admin/new'
      path: '/new'
      fullPath: '/admin/new'
      preLoaderRoute: typeof AuthenticatedAdminNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/edit/$id': {
      id: '/_authenticated/admin/edit/$id'
      path: '/edit/$id'
      fullPath: '/admin/edit/$id'
      preLoaderRoute: typeof AuthenticatedAdminEditIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminNewRoute: typeof AuthenticatedAdminNewRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminEditIdRoute: typeof AuthenticatedAdminEditIdRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminNewRoute: AuthenticatedAdminNewRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminEditIdRoute: AuthenticatedAdminEditIdRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedCuentaRoute: typeof AuthenticatedCuentaRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedCuentaRoute: AuthenticatedCuentaRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CarritoRoute: CarritoRoute,
  CatalogoRoute: CatalogoRoute,
  CheckoutRoute: CheckoutRoute,
  CheckoutResultadoRoute: CheckoutResultadoRoute,
  ProductoSlugRoute: ProductoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
